name: Deploy Docker Container

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo dockerd &
          sleep 10  # Aguarda o daemon do Docker iniciar

      - name: Verificar Docker
        run: |
          if ! docker --version; then
            echo "Docker não está instalado corretamente";
            exit 1;
          fi

      - name: Construir imagem Docker
        run: |
          docker build -t meu-app .

      - name: Rodar o contêiner
        run: |
          docker run -d -p 5000:5000 meu-app

      - name: Limpar recursos (opcional)
        if: always()
        run: |
          docker container prune -f
          docker image prune -f
