name: Deploy Linux Container

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar instalação do Docker
        run: |
          if !(docker --version > /dev/null 2>&1); then
            echo "Docker not found. Please ensure Docker is installed and running."
            exit 1
          fi

      - name: Atualizar e instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix

      - name: Construir imagem Docker
        run: |
          docker build --build-arg USERNAME=${{ secrets.USERNAME }} --build-arg PASSWORD=${{ secrets.PASSWORD }} -t meu-linux-container .

      - name: Criar diretório para volume
        run: |
          mkdir -p ~/conteiner/Documents

      - name: Rodar contêiner Linux com volume
        run: |
          docker run -dit --name linux-dev -v ~/conteiner/Documents:/mnt meu-linux-container

      - name: Criar e executar script no contêiner
        run: |
          # Criar script
          scriptPath=~/conteiner/Documents/script.sh
          mkdir -p ~/conteiner/Documents
          echo '#!/bin/bash' > $scriptPath
          echo 'useradd -m -s /bin/bash convidado' >> $scriptPath
          echo 'passwd -d convidado' >> $scriptPath
          echo 'echo "Por favor, defina uma senha para o usuário convidado:"' >> $scriptPath
          echo 'passwd convidado' >> $scriptPath

          # Ajustar permissões e executar script
          dos2unix $scriptPath
          chmod +x $scriptPath
          docker cp $scriptPath linux-dev:/mnt/script.sh
          docker exec linux-dev bash /mnt/script.sh

      - name: Iniciar terminal dentro do contêiner como usuário convidado
        run: |
          docker exec -it --user convidado linux-dev bash
